# Generated by Django 2.0 on 2017-12-13 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171212_0627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'blog_Categories'},
        ),
        migrations.AlterModelTable(
            name='categories',
            table='blog_categories',
        ),
    ]
